accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'


urlpatterns = [
    path('', views.details, name='details'),
    path('details/<username>/', views.details, name='details'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('password-change', views.PasswordChangeView.as_view(), name='password-change'),
    path('password-change-done', views.PasswordChangeDoneView.as_view(), name='password-change-done'),

    path('password-reset/', views.PasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('password-reset/complete', views.PasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

django_super/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls.core')),
]

norrep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls.core')),
]

super/urls.py
from django.urls import path

from .views import home


app_name = 'super'


urlpatterns = [
    path('', home, name='home')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class AccountManager(BaseUserManager):

    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have an username')
        
        user = self.model(
            email=self.normalize_email(email),
            username=username
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(email, username, password)

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name='email', unique=True, max_length=60)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = AccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django import forms
from django.contrib.auth import get_user_model, password_validation


class RegisterForm(UserCreationForm):

    username = forms.CharField(label='Username', widget=forms.TextInput())
    email = forms.CharField(label='Email', widget=forms.EmailInput())
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))

    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Email or username', widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    error_messages = {
        'invalid_login': "Please enter the correct %(username)s and password.",
        'inactive': "This account is inactive."
    }

class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label= "Old password", strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True}),
    )
    new_password1 = forms.CharField(
        label= "New password",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label= "New password confirmation",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )
    error_messages = {
        'password_incorrect': "Your old password was entered incorrectly.",
    }


class PasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )


class PasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label= "New password",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label= "New password confirmation",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render

from .models import Account
from .forms import LoginForm, PasswordResetConfirmForm, RegisterForm, PasswordChangeForm, PasswordResetForm


EXTRA_CONTEXT = {
    'scss_path': 'accounts/style/accounts.scss',
    'ts_path': 'accounts/script/accounts.ts'
}


class RegisterView(generic.CreateView):
    template_name = 'accounts/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('accounts:login')
    extra_context = EXTRA_CONTEXT

    def get_success_url(self):
        messages.add_message(self.request,messages.SUCCESS, "Your account have been created successfully!")
        return super().get_success_url()


class LoginView(views.LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginForm
    extra_context = EXTRA_CONTEXT


class LogoutView(views.LogoutView):
    template_name = 'accounts/logout.html'
    extra_context = EXTRA_CONTEXT


class PasswordChangeView(views.PasswordChangeView):
    template_name = 'accounts/password/password-change.html'
    success_url = reverse_lazy('accounts:password-change-done')
    form_class = PasswordChangeForm
    extra_context = EXTRA_CONTEXT


class PasswordChangeDoneView(views.PasswordChangeDoneView):
    template_name = 'accounts/password/password-change-done.html'
    extra_context = EXTRA_CONTEXT


class PasswordResetView(views.PasswordResetView):
    template_name = 'accounts/password/password-reset.html'
    success_url = reverse_lazy('accounts:password-reset-done')
    email_template_name = 'accounts/password/password-reset-email.html'
    subject_template_name = 'accounts/password/password-reset-subject.txt'
    form_class = PasswordResetForm
    extra_context = EXTRA_CONTEXT


class PasswordResetDoneView(views.PasswordResetDoneView):
    template_name = 'accounts/password/password-reset-done.html'
    extra_context = EXTRA_CONTEXT


class PasswordResetConfirmView(views.PasswordResetConfirmView):
    template_name = 'accounts/password/password-reset-confirm.html'
    success_url = reverse_lazy('accounts:password-reset-complete')
    form_class = PasswordResetConfirmForm
    extra_context = EXTRA_CONTEXT


class PasswordResetCompleteView(views.PasswordResetCompleteView):
    template_name = 'accounts/password/password-reset-complete.html'
    extra_context = EXTRA_CONTEXT


@login_required
def details(request, username=''):
    messages.success(request, "This is a test messages to test the styling of the website.", extra_tags={'expire':True})
    if username == '':
        return render(request, 'accounts/details.html', context={'user': request.user, **EXTRA_CONTEXT})
    
    try:
        user = Account.objects.get(username=username)
    except Account.DoesNotExist:
        return render(request, 'accounts/details.html', context={'username': username, **EXTRA_CONTEXT})
    return render(request, 'accounts/details.html', context={'user': user, **EXTRA_CONTEXT})

accounts/templates/accounts/details.html
{% extends "super/super.html" %}

{% block title %}Account details{% endblock %}

{% block content %}
<div class="form-container">
    <div id="details-box">
        <a alt="Logout" class="top-right-button" href="{% url 'accounts:logout' %}">&#8689;</a>
        {% if not username %}
        <h3>{{user.username}}'s account</h3>
        <ul>
            <li>Joined date:   {{user.date_joined}}</li>
            <li>Last login:   {{user.last_login}}</li>
        </ul>
        
        {% else %}
        <h3>Could not find the user {{username}}!</h3>
        {% endif %}
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "super/super.html" %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="form-container">
    <div class="form-box">
        <img class="form-icon" src="{% static 'super/img/favicon.svg' %}" alt="">
        <h3 class="form-title">Connection</h3>
        <form method="post">
            {% csrf_token %}
            <div class="form-field">
                <label class="field-label" for="{{form.username.id_for_label}}">Email or username</label>
                {{ form.username }}
                {{ form.username.errors }}
            </div>

            <div class="form-field">
                <label class="field-label" for="{{form.password.id_for_label}}">Password</label>
                {{ form.password }}
                <div class="error-msg-container">
                    {{ form.non_field_errors }}
                </div>
                <a class="link-password-reset" href="{% url 'accounts:password-reset' %}">I forgot my password</a>
                {{ form.password.errors }}
            </div>
            
            <div class="form-buttons">
                <a href="{% url 'accounts:register' %}">Create an account</a>
                <button type="submit">Continue</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "super/super.html" %}
{% load static %}

{% block content %}
<div class="form-container">
    <div class="form-box info-box">
        <img class="form-icon" src="{% static 'super/img/favicon.svg' %}" alt="">
        <h3 class="form-title">You have logged out successfully!</h3>
        <p>Do you want to <a href="{% url 'accounts:login' %}">login again</a>?</p>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "super/super.html" %}
{% load static %}
{% block title %}Registration{% endblock %}

{% block content %}
<div class="form-container">
    <div id="registration-form-box" class="form-box">
        <img class="form-icon" src="{% static 'super/img/favicon.svg' %}" alt="">
        <h3 class="form-title">Registration</h3>
        <form method="post">
            {% csrf_token %}
            <div class="form-field">
                <label class="field-label" for="{{form.username.id_for_label}}">Username</label>
                {{ form.username }}
                {{ form.username.errors }}
            </div>

            <div class="form-field">
                <label class="field-label" for="{{form.email.id_for_label}}">Email</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>

            <div class="form-field">
                <label class="field-label" for="{{form.password1.id_for_label}}">Set a password</label>
                {{ form.password1 }}
                {{ form.password1.errors }}
            </div>
            <div class="form-field">
                <label class="field-label" for="{{form.password2.id_for_label}}">Confirm password</label>
                {{ form.password2 }}
                <div class="error-msg-container">
                    {{ form.non_field_errors }}
                </div>
                {{ form.password2.errors }}
            </div>
            
            <div class="form-buttons">
                <a href="{% url 'accounts:login' %}">Login instead</a>
                <button type="submit">Continue</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}